steps:
  - name: 'eu.gcr.io/cloud-builders/docker'
    id: 'Build and Push Docker Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Build the image and tag with the commit SHA
        docker build -t "eu.gcr.io/$PROJECT_ID/mcp-tools:$COMMIT_SHA" .

        # If on the main branch, also tag the image with 'trunk'
        if [ "$BRANCH_NAME" = "main" ]; then
          docker tag "eu.gcr.io/$PROJECT_ID/mcp-tools:$COMMIT_SHA" "eu.gcr.io/$PROJECT_ID/mcp-tools:trunk"
        fi

        # Push all tags for the repository
        docker push --all-tags "eu.gcr.io/$PROJECT_ID/mcp-tools"

# Store the image name for later use in deployments.
# The 'trunk' tagged image will only be pushed for builds on the 'main' branch.
images:
  - 'eu.gcr.io/$PROJECT_ID/mcp-tools:$COMMIT_SHA'
  - 'eu.gcr.io/$PROJECT_ID/mcp-tools:trunk'

options:
  logging: CLOUD_LOGGING_ONLY